pipeline {
    agent any 

       stages {
        
       stage('Unit Tests') {
            when {
                branch 'dev' 
            }
            steps {
                dir('javaapp-pipeline') {
                sh 'mvn clean test'
            }
            }
        }
}
